package com.capgemini.AdminAPI.entities;

import java.util.Date;
import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.capgemini.AdminAPI.beans.ScreenTime;

@DynamoDBTable(tableName = "Screens")
public class Screen {
	
	private String screenId;
	private String theaterId;
	private String screenName;
	private String movieDimension;
	private Date dateOfTheShow;
	private List<ScreenTime> screenTimes;
	
	public Screen() {
		// Default Constructor
	}

	public Screen(String theaterId, String screenName, String movieDimension, Date dateOfTheShow,
			List<ScreenTime> screenTimes) {
		super();
		this.theaterId = theaterId;
		this.screenName = screenName;
		this.movieDimension = movieDimension;
		this.dateOfTheShow = dateOfTheShow;
		this.screenTimes = screenTimes;
	}

	@DynamoDBAttribute
	public String getTheaterId() {
		return theaterId;
	}

	public void setTheaterId(String theaterId) {
		this.theaterId = theaterId;
	}

	@DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
	public String getScreenId() {
		return screenId;
	}

	public void setScreenId(String screenId) {
		this.screenId = screenId;
	}

	@DynamoDBAttribute
	public String getScreenName() {
		return screenName;
	}

	public void setScreenName(String screenName) {
		this.screenName = screenName;
	}

	@DynamoDBAttribute
	public String getMovieDimension() {
		return movieDimension;
	}

	public void setMovieDimension(String movieDimension) {
		this.movieDimension = movieDimension;
	}

	@DynamoDBAttribute
	public Date getDateOfTheShow() {
		return dateOfTheShow;
	}

	public void setDateOfTheShow(Date dateOfTheShow) {
		this.dateOfTheShow = dateOfTheShow;
	}

	@DynamoDBAttribute
	public List<ScreenTime> getScreenTimes() {
		return screenTimes;
	}

	public void setScreenTimes(List<ScreenTime> screenTimes) {
		this.screenTimes = screenTimes;
	}

}
